Kong 1.0 (#22)
* Migrate to Kong 1.0

* Temporary workaround for OpenResty/Nginx compile error "undefined reference to pthread_atfork"

* Fix so prerelease sees an empty database

* Use Kong 1.0.0rc2 pre-compiled runtime archive

* 📚 correct the Kong version

* 📚 correct the Kong version

* Fix so runtime will start-up when database is not available

* Clarify release error message when databse is not yet configured

* Improve runtime config by switching listener & DB config to env vars

* 📚 Kong 1.0.0rc3

* kong.conf runtime config file still seems to be required for some commands, bring it back, better than ever

* Debug log Kong config files (temporary, leaks secrets)

* Fix to trigger error message when database is not yet configured

* Implicitly source Kong runtime config in release phase

* Fix debug log Kong config files (temporary, leaks secrets)

* Undo: Debug log Kong config files

* Fix broken Nginx listener config

* Fix env vars export

* Undo error message when database is not yet configured

* Use Kong 1.0.0rc3 pre-compiled runtime archive

* Update bin/test for Kong 1.0

* Update test runner based on upstream Kong

* Fix so only Postgres is used for tests

* Debug output test environment to logs

* Execute Kong profile script after others; fix to get DATABASE_URL w/ Heroku CI in-dyno database

* Undo debugging & work-around for DATABASE_URL in CI (fixed in platform)

* Remove libc package (unneeded from earlier debugging)

* Use Kong 1.0.0 (pre-release commit 0f2d77b) pre-compiled runtime archive.